# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12c68107a2a99cb510fbb140e96c6108fc96a61b4952d2c8e392d17af4c8fcaeb4057d92f379bb0ae7362096cd8d957d5b96b8fd31d1a9358c3f415c8c712333

test:
  secret_key_base: 373cae9226cdc4e3db1b637b38fceb3d663a4084bef26a1de955103994de5110ca6f394028ec0ea96027ad57e42d9c24d3a4a95184f0e7d3eb12f6f9f993c026

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
